Transform: AWS::Serverless-2016-10-31
Description: A API backend composed of various serverless applications for use with stemplayer-js

Conditions:
  CreateBucket: !Not [!Equals [!Ref ExistingBucket, true]]

Parameters:
  StageName:
    Type: String
    Default: dev
  LogLevel:
    Type: String
    Default: info
  SwsSecret:
    Type: String
    NoEcho: true
  StorageBucketName:
    Description: The name for the storage bucket. Ensure the name is sufficiently unique to avoid name clash.
    Type: String
  ExistingBucket:
    Type: String
    Description: Whether to create the audio bucket or use a pre-existing bucket
    AllowedValues:
      - true
      - false
    Default: false
  AllowedAudioOrigins:
    Type: String
    Description: Origins from which the service can source audio
    Default: "*"
  CORSAllowedOrigins:
    Description: The permitted origins for which CORS headers will be added to responses
    Type: String
    Default: "*"
  AudioCacheTtl:
    Type: Number
    Description: Determines how long unused processed audio is held before its removed from the audio bucket. Default 30 days.
    Default: "31104000" # 1 Year
  SignedUrlExpirySec:
    Type: String
    Description: The duration of the signed urls to the audio
    Default: 86400 # 24 hours

Resources:
  fcaudiotoolslambdalayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/fc-audio-tools-lambda-layer
        SemanticVersion: 1.0.6-beta.3

  fcaudiowaveformlambdalayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/fc-audiowaveform-lambda-layer
        SemanticVersion: 1.0.6-beta.3

  fclambdabearerauthorizer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/fc-lambda-bearer-authorizer
        SemanticVersion: 0.0.3-beta.4
      Parameters:
        JwtAudience: stemplayer-js-api
        SwsSecret: !Ref SwsSecret

  fcaudiomixservice:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/fc-audio-mix-service
        SemanticVersion: 3.0.3-beta.5
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        SwsSecret: !Ref SwsSecret
        AudioToolsLayerArn: !GetAtt fcaudiotoolslambdalayer.Outputs.LayerVersion
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        BucketName: !Ref StorageBucketName
        ExistingBucket: true
        AuthorizerArn: !GetAtt fclambdabearerauthorizer.Outputs.LambdaAuthorizerFunctionArn

  fchlsservice:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/fc-hls-service
        SemanticVersion: 3.2.0-beta.3
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        AudioToolsLayerArn: !GetAtt fcaudiotoolslambdalayer.Outputs.LayerVersion
        AllowedAudioOrigins: !Ref AllowedAudioOrigins
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        AllowedFormats: "mp3,oga"
        AllowedBitrates: 128,96
        AllowedSamplerates: 44100,48000
        BucketName: !Ref StorageBucketName
        ExistingBucket: true
        AllowedSegmentDuration: 5
        AudioCacheTtl: !Ref AudioCacheTtl
        SignedUrlExpirySec: !Ref SignedUrlExpirySec
        AuthorizerArn: !GetAtt fclambdabearerauthorizer.Outputs.LambdaAuthorizerFunctionArn

  fcaudiowaveformservice:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/fc-audio-waveform-service
        SemanticVersion: 3.0.3-beta.6
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        AudiowaveformLayerArn: !GetAtt fcaudiowaveformlambdalayer.Outputs.LayerVersion
        AllowedAudioOrigins: !Ref AllowedAudioOrigins
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        BucketName: !Ref StorageBucketName
        ExistingBucket: true
        AuthorizerArn: !GetAtt fclambdabearerauthorizer.Outputs.LambdaAuthorizerFunctionArn

  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: CreateBucket
    Properties:
      BucketName: !Ref StorageBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  AudioMixServiceEndpoint:
    Description: "The endpoint to the audio-mix-service"
    Value: !GetAtt fcaudiomixservice.Outputs.ServiceApi
  HlsServiceEndpoint:
    Description: "The endpoint to the hls-service"
    Value: !GetAtt fchlsservice.Outputs.ServiceApi
  AudioWaveformServiceEndpoint:
    Description: "The endpoint to the audiowaveform-service"
    Value: !GetAtt fcaudiowaveformservice.Outputs.ServiceApi
  SwsSecret:
    Description: "The secret"
    Value: !Ref SwsSecret

Metadata:
  AWS::ServerlessRepo::Application:
    Name: stemplayer-js-api
    Description: >
      A nested stack of certain serverless microservices to provide the stemplayer with backend powers
    Author: Team First Coders
    ReadmeUrl: README.md
    SpdxLicenseId: AGPL-3.0-or-later
    LicenseUrl: LICENSE
    Labels: ["layer", "lambda", "serverless", "waveform", "stemplayer-js"]
    HomePageUrl: https://github.com/stemplayer-js/api
    SourceCodeUrl: https://github.com/stemplayer-js/api
    SemanticVersion: 1.0.0 # overwritten by sam publish cli command
