Transform: AWS::Serverless-2016-10-31
Description: A API backend composed of various serverless applications for use with stemplayer-js

Parameters:
  StageName:
    Type: String
    Default: dev
  LogLevel:
    Type: String
    Default: info
  SwsSecret:
    Type: String
    NoEcho: true
  CloudfrontPrivateKey:
    Type: String
    Default: ""
  CloudfrontKeypairId:
    Type: String
    Default: ""
  StorageBucketName:
    Type: String
  AllowedAudioOrigins:
    Type: String
    Description: Origins from which the service can source audio
    Default: "*"
  CORSAllowedOrigins:
    Type: String
    Default: "*"
  AudioCacheTtl:
    Type: Number
    Description: Determines how long unused processed audio is held before its removed from the audio bucket. Default 30 days.
    Default: "31104000" # 1 Year
  SignedUrlExpirySec:
    Type: String
    Description: The duration of the signed urls to the audio
    Default: 86400 # 24 hours

Resources:
  soundwsaudiotoolslambdalayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/soundws-audio-tools-lambda-layer
        SemanticVersion: 1.0.4-beta.1

  soundwsaudiowaveformlambdalayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/soundws-audiowaveform-lambda-layer
        SemanticVersion: 1.0.4-beta.1

  soundwsaudiomixservice:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/soundws-audio-mix-service
        SemanticVersion: 3.0.1-beta.4
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        SwsSecret: !Ref SwsSecret
        AudioToolsLayerArn: !GetAtt soundwsaudiotoolslambdalayer.Outputs.LayerVersion
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        BucketName: !Ref StorageBucketName
        ExistingBucket: true

  soundwshlsservice:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/soundws-hls-service
        SemanticVersion: 3.1.0-beta.0
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        SwsSecret: !Ref SwsSecret
        AudioToolsLayerArn: !GetAtt soundwsaudiotoolslambdalayer.Outputs.LayerVersion
        CloudfrontPrivateKey: !Ref CloudfrontPrivateKey
        CloudfrontKeypairId: !Ref CloudfrontKeypairId
        AllowedAudioOrigins: !Ref AllowedAudioOrigins
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        AllowedFormats: "mp3,oga"
        AllowedBitrates: 128,96
        AllowedSamplerates: 44100,48000
        BucketName: !Ref StorageBucketName
        ExistingBucket: true
        AllowedSegmentDuration: 5
        AudioCacheTtl: !Ref AudioCacheTtl
        SignedUrlExpirySec: !Ref SignedUrlExpirySec

  soundwsaudiowaveformservice:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:715905027390:applications/soundws-audio-waveform-service
        SemanticVersion: 3.0.1-beta.4
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        SwsSecret: !Ref SwsSecret
        AudiowaveformLayerArn: !GetAtt soundwsaudiowaveformlambdalayer.Outputs.LayerVersion
        AllowedAudioOrigins: !Ref AllowedAudioOrigins
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        BucketName: !Ref StorageBucketName
        ExistingBucket: true

  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref StorageBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  AudioMixServiceEndpoint:
    Description: "The endpoint to the audio-mix-service"
    Value: !GetAtt soundwsaudiomixservice.Outputs.ServiceApi
  HlsServiceEndpoint:
    Description: "The endpoint to the hls-service"
    Value: !GetAtt soundwshlsservice.Outputs.ServiceApi
  AudioWaveformServiceEndpoint:
    Description: "The endpoint to the audiowaveform-service"
    Value: !GetAtt soundwsaudiowaveformservice.Outputs.ServiceApi
  SwsSecret:
    Description: "The secret"
    Value: !Ref SwsSecret

Metadata:
  AWS::ServerlessRepo::Application:
    Name: stemplayer-js-api
    Description: >
      A nested stack of certain serverless microservices to provide the stemplayer with backend powers
    Author: Team First Coders
    ReadmeUrl: README.md
    SpdxLicenseId: AGPL-3.0-or-later
    LicenseUrl: LICENSE
    Labels: ["layer", "lambda", "serverless", "waveform", "stemplayer-js"]
    HomePageUrl: https://github.com/stemplayer-js/api
    SourceCodeUrl: https://github.com/stemplayer-js/api
    SemanticVersion: 1.0.0 # overwritten by sam publish cli command
