Transform: AWS::Serverless-2016-10-31
Description: SoundWs API

Parameters:
  StageName:
    Type: String
    Default: dev
  LogLevel:
    Type: String
    Default: info
  SwsSecret:
    Type: String
    NoEcho: true
  CloudfrontPrivateKey:
    Type: String
    Default: ""
  CloudfrontKeypairId:
    Type: String
    Default: ""
  StorageBucketName:
    Type: String
  AllowedAudioOrigins:
    Type: String
    Description: Origins from which the service can source audio
    Default: "*"
  CORSAllowedOrigins:
    Type: String
    Default: ""

Resources:
  AudioToolsLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: node_modules/@soundws/audio-tools-lambda-layer/template.yaml

  AudiowaveformLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: node_modules/@soundws/audiowaveform-lambda-layer/template.yaml

  AudioMixService:
    Type: AWS::Serverless::Application
    Properties:
      Location: node_modules/@soundws/audio-mix-service/dist/template.yaml
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        SwsSecret: !Ref SwsSecret
        AudioToolsLayerArn: !GetAtt AudioToolsLayer.Outputs.LayerVersion
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        BucketName: !Ref StorageBucket
        ExistingBucket: true

  HlsService:
    Type: AWS::Serverless::Application
    Properties:
      Location: node_modules/@soundws/hls-service/dist/template.yaml
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        SwsSecret: !Ref SwsSecret
        AudioToolsLayerArn: !GetAtt AudioToolsLayer.Outputs.LayerVersion
        CloudfrontPrivateKey: !Ref CloudfrontPrivateKey
        CloudfrontKeypairId: !Ref CloudfrontKeypairId
        AllowedAudioOrigins: !Ref AllowedAudioOrigins
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        AllowedFormats: "mp3,oga"
        AllowedBitrates: 128,96
        AllowedSamplerates: 44100,48000
        BucketName: !Ref StorageBucket
        ExistingBucket: true
        AllowedSegmentDuration: 5

  WaveformService:
    Type: AWS::Serverless::Application
    Properties:
      Location: node_modules/@soundws/audio-waveform-service/dist/template.yaml
      Parameters:
        LogLevel: !Ref LogLevel
        StageName: !Ref StageName
        SwsSecret: !Ref SwsSecret
        AudiowaveformLayerArn: !GetAtt AudiowaveformLayer.Outputs.LayerVersion
        AllowedAudioOrigins: !Ref AllowedAudioOrigins
        CORSAllowedOrigins: !Ref CORSAllowedOrigins
        BucketName: !Ref StorageBucket
        ExistingBucket: true

  # This is to ensure that API keys are required for all non OPTIONS resources
  EnableApiKeysForMethods:
    Type: AWS::Serverless::Application
    Properties:
      Location: node_modules/@soundws/custom-cf-resource-require-key-for-methods/dist/template.yaml
      TimeoutInMinutes: 5
      Parameters:
        StageName: !Ref StageName
        ApiIds:
          !Join [
            ",",
            [
              !GetAtt AudioMixService.Outputs.ApiId,
              !GetAtt HlsService.Outputs.ApiId,
              !GetAtt WaveformService.Outputs.ApiId,
            ],
          ]

  AutoSetLogRetention:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/auto-set-log-group-retention
        SemanticVersion: 1.5.0
      Parameters:
        # The number of days to retain logs in CloudWatch Logs for.
        RetentionDays: "30"

  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref StorageBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FullLicenseUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      Description: Usage plan for full usage
      UsagePlanName: Full
      ApiStages:
        - ApiId: !GetAtt AudioMixService.Outputs.ApiId
          Stage: !Ref StageName
        - ApiId: !GetAtt HlsService.Outputs.ApiId
          Stage: !Ref StageName
        - ApiId: !GetAtt WaveformService.Outputs.ApiId
          Stage: !Ref StageName
      Quota:
        Limit: 50000
        Period: DAY
      Throttle:
        BurstLimit: 5000
        RateLimit: 1000

  TrialUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      Description: Usage plan for trial
      UsagePlanName: Trial
      ApiStages:
        - ApiId: !GetAtt AudioMixService.Outputs.ApiId
          Stage: !Ref StageName
        - ApiId: !GetAtt HlsService.Outputs.ApiId
          Stage: !Ref StageName
        - ApiId: !GetAtt WaveformService.Outputs.ApiId
          Stage: !Ref StageName
      Quota:
        Limit: 1000
        Period: MONTH
      Throttle:
        BurstLimit: 100
        RateLimit: 25

Outputs:
  AudioMixServiceEndpoint:
    Description: "The endpoint to the audio-mix-service"
    Value: !GetAtt AudioMixService.Outputs.ServiceApi
  HlsServiceEndpoint:
    Description: "The endpoint to the hls-service"
    Value: !GetAtt HlsService.Outputs.ServiceApi
  AudioWaveformServiceEndpoint:
    Description: "The endpoint to the audiowaveform-service"
    Value: !GetAtt WaveformService.Outputs.ServiceApi
  SwsSecret:
    Description: "The secret"
    Value: !Ref SwsSecret
